name: Inter-branch merge workflow
on:
  push:
    branches:
      - release/**

permissions:
  contents: write
  pull-requests: write

jobs:
  Merge:
    uses: dotnet/arcade/.github/workflows/backport-base.yml@8101e33d23b03c5d8bafa2b1502a69dec9901a30 # 2024-06-24
